// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.Postion;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Postion_Roo_Configurable {
    
    declare @type: Postion: @Configurable;
    
}
